name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (example step)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     echo "Running test cases..."
      #     # python -m unittest discover

  commit-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dummy commit step
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          echo "# Timestamp" >> timestamp.txt
          date >> timestamp.txt
          git add .
          git commit -m "GitHub Action commit: update timestamp" || echo "No changes to commit"
          git push origin main
